name: Publish release

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Create release
      id: create_release
      uses: "softprops/action-gh-release@v1"
      with:
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - uses: actions/checkout@v3
    - name: Pre-requesites
      run: sudo apt-get install pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev
    - name: Run build
      run: cargo build --release && strip --strip-all ./target/release/togglebit && mv ./target/release/togglebit ./target/release/togglebit-linux

    - name: Upload release
      id: upload-release-linux
      uses: alexellis/upload-assets@0.2.3
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_paths: '["./target/release/togglebit-linux"]'


  build-macos:
    runs-on: macos-latest
    needs: release

    steps:
    - uses: actions/checkout@v3
    - name: Run build
      run: cargo build --release && mv ./target/release/togglebit ./target/release/togglebit-macos

    - name: Upload release
      id: upload-release-linux
      uses: alexellis/upload-assets@0.2.3
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_paths: '["./target/release/togglebit-macos"]'


  build-windows:
    runs-on: windows-2019
    needs: release

    steps:
    - uses: actions/checkout@v3

    - name: Run build
      run: cargo build --release

    - name: Upload release
      id: upload-release-windows
      uses: alexellis/upload-assets@0.2.3
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_paths: '["./target/release/togglebit.exe"]'
